# Generated by Django 3.0.1 on 2020-01-05 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='glass',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredient1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredient2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredient3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredient4',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='measure1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='measure2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='measure3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='measure4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='photo_main',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='description',
            field=models.TextField(),
        ),
    ]
