# Generated by Django 3.0.1 on 2020-01-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_auto_20200105_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='measure1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='measure2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='measure3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='measure4',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
